apiVersion: v1
kind: Secret
metadata:
  name: mysql-auth
type: Opaque
data:
    MYSQL_ROOT_PASSWORD: cHJvamVjdGFwcA==
    MYSQL_DATABASE: cHJvamVjdGFwcC1kYg==
    MYSQL_USER: cHJvamVjdGFwcA==
    MYSQL_PASSWORD: QXAyLUVuL3c=
