apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  volumes:
    # Add the ConfigMap we declared above as a volume for the pod
    - name: mysql-config-volume
      configMap:
        name: mysql-config
        items:
        - key: my.cnf
          path: my.cnf

  containers:
  - name: mysql
    image: mysql:8.0
    envFrom:
    - secretRef:
        name: mysql-auth
    ports:
    - containerPort: 3306
    volumeMounts:
      - name: mysql-config-volume
        mountPath: /etc/mysql/conf.d/
